### ISSUE TITLE
Week 3 Homework

### ISSUE THREAD

**Issue by kevinmccartney** [mleo2857/js-app-dev-week-3#1]
Hey Mike!

Just a couple items to check up on for this week -

1. Complete the Functional JavaScript Nodeschool module & upload a screenshot.
2. In `playersExercise.js`, on line 11, it is asking you to `find` *a* player with the name Mike. This means we should only return one.
3. In `slideshowWithIntervals.js`, add the pause function to the `prevPhoto` method.

**Comment by mleo2857** [comment]
Updated issues. Still working on Functional Javascript. Thanks

**Comment by kevinmccartney** [comment]
Looks good, thanks for updating these! I'm going to close this issue since we're going to be working through the Functional JS module together in class.
